apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: peykzd94l-nodejs-gitops
  description: This is GitOps manifest for peykzd94l-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: peykzd94l-nodejs
    janus-idp.io/tekton: peykzd94l-nodejs 
    backstage.io/kubernetes-id: peykzd94l-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:peykzd94l-nodejs
